# Generated by Django 3.0.3 on 2020-04-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200410_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='autherName',
        ),
    ]
