# Generated by Django 3.0.3 on 2020-04-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_book_auther'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='auther',
        ),
    ]
