# Generated by Django 3.0.3 on 2020-04-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_book_auther_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther_name',
            new_name='books_auther',
        ),
    ]
