# Generated by Django 3.0.3 on 2020-04-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20200410_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='books_auther',
        ),
        migrations.AddField(
            model_name='book',
            name='writter',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
