# Generated by Django 3.0.3 on 2020-04-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_auto_20200410_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='writter',
        ),
        migrations.AddField(
            model_name='book',
            name='Books_auther_name',
            field=models.CharField(default=None, max_length=36),
        ),
    ]
