# Generated by Django 3.0.3 on 2020-04-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_auto_20200410_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Books_auther_name',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
