# Generated by Django 3.0.3 on 2020-04-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_auto_20200410_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='discription',
            field=models.TextField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='NA', max_length=36),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='writter',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
